Applausable/urls.py
from django.contrib import admin
from django.urls import path, re_path, include, reverse
from django.conf.urls import url
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('applausable:register_profile')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('applausable/', include('rango.urls')),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/urls.py
from django.urls import path
from django.conf.urls import url
from rango import views

app_name = 'applausable'

urlpatterns = [
    path('home/artist/', views.artist, name='artist'),
    path('home/specificArtist/<slug:artist_name_slug>/', views.show_artist, name='show_artist'),
    path('home/album/<slug:album_name_slug>/', views.show_album, name='show_album'),
    path('home/song/<slug:song_name_slug>/', views.show_song, name='show_song'),
    path('user/', views.show_user, name='show_user'),
    path('home/genre/<genre_name>/', views.show_genre, name='show_genre'),
    path('home/allGenres/', views.all_genre, name='all_genre'),
    path('add_artist/', views.add_artist, name='add_artist'),
    path('artist/<slug:artist_name_slug>/add_album/', views.add_album, name='add_album'),
    path('album/<slug:album_name_slug>/add_song/', views.add_song, name='add_song'),
    path('song/<slug:song_name_slug>/add_review/', views.add_review, name='add_review'),
    # Accounts templates are being used instead (url link found in other dir)
    #path('logout/', views.logout, name='logout'),
    #path('home/login/', views.login, name='login'),
    #path('home/signup/', views.signup, name='signup'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('searchResults/', views.SearchResultsView, name='search_results'),
    path('highestReviewedSongs/', views.highestReviewedSongs, name='highestReviewedSongs'),
]

templates/applausable/SignUp.html
<!DOCTYPE html>
<html>
<head>
    <title>SignUp</title>
</head>

<body>
    <h1>SignUp.</h1>
    <div>
        <a href="/home/artist/">Artist</a>
    </div>
</body>

</html>

templates/applausable/add_album.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}




{% block title_block %}
 Add a Album
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add an Album</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form role="form" id="album_form" method="post" action="{% url 'applausable:add_album' artist.slug  %}" enctype = "multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit"> 
                    Add Album 
                </button>
                <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/applausable/add_artist.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Artist
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add an Artist</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form role="form" id="artist_form" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit"> 
                    Add Artist 
                </button>
                <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/applausable/add_review.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
 Add a Review
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Review</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form role="form" id="review_form" method="post" action="{% url 'applausable:add_review' song.slug  %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Review
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/applausable/add_song.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
 Add a Album
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Song</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form role="form" id="song_form" method="post" action="{% url 'applausable:add_song' album.slug  %}" >
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}<br />
            {{ field }}<br />
            <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">
                Add Song
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/applausable/album.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Album
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">

<div class="jumbotron">
    <div class="text-center">
        {% if album %}

        <h1>{{ album.albumName }}</h1>
	

        {% if album.artistName %}
        <br />
        <a href="{% url 'applausable:show_artist' album.artistID.slug %}">
            <h4>by {{ album.artistName }}</h4>
        </a>
        {% endif %}

        {% if overallScore %}
        <br />
        <h2> Album Score: {{overallScore.overallScore__avg|floatformat}}/10</h2>
        {% endif %}


        {% else %}
        <h1>No album found</h1>
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="card">
        <br />
        <img src="{{ MEDIA_URL }}{{ album.albumCover }}"  width="400" height="400" alt="{{ artist.artistName }}'s profile image">
        <div class="card-body">
          <h4 class="card-title" align="center">{{ album.albumName }}</h4>
          <br />
          <div class="container">

              <br />

              <table class="table table-hover">
                  <thead>
                      <tr>
                          <th scope="col">#</th>
                          <th scope="col">Song</th>
                          <th scope="col">Artist</th>
                          <th scope="col">Score</th>
                          <th scope="col">Link</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% if songs %}
                      {% for song in songs %}
                      <tr>
                          <th scope="row">{{ forloop.counter }}</th>
                          <td>{{ song.title }}</td>
                          <td>{{ song.artistName }}</td>
                          <td>{{ song.overallScore }}</td>
                          <td><a class="nav-link active" href="{% url 'applausable:show_song' song.slug %}">Learn More</a> </td>
                      </tr>
                      {% endfor %}
                      {% else %}
                      This album has no songs.
                      {% endif %}
                  </tbody>
              </table>
          </div>
          
       
          
          {% if request.user.is_superuser %}
          <br />
          <a href="{% url 'applausable:add_song' album.slug %}">Add Song</a>
          {% endif %}
        </div>
    </div>
    <br />
</div>



<br />

<div class="container" align="center">
    <br />


    <a href="{% url 'applausable:show_artist' album.artistID.slug %}">
        <p>Back to Artist: {{ album.artistID.artistName }}</p>
    </a>
</div>

{% endblock %}

templates/applausable/allGenres.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Genres
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/photo_test.css' %}">

<div class='jumbotron jumbotron-fluid'>
    <div class='container'>
        <h1>Genres:</h1>
    </div>
</div>


<table cellpadding="25" align="center">
    <tr>
        <td>
            <a class="photo" id="photo" href="{% url 'applausable:show_genre' 'Pop' %}">

                <img src="{% static 'genre_images/Pop.PNG' %}"
                     width="150"
                     height="150" alt="Pop Image" />

            </a>
        </td>

        <td>
            <a href="{% url 'applausable:show_genre' 'Rock' %}">

                <img src="{% static 'genre_images/Rock.PNG' %}"
                     width="150"
                     height="150" alt="Rock Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Soul' %}">

                <img src="{% static 'genre_images/Soul.PNG' %}"
                     width="150"
                     height="150" alt="Soul Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Jazz' %}">

                <img src="{% static 'genre_images/Jazz.PNG' %}"
                     width="150"
                     height="150" alt="Jazz Image" />

            </a>
        </td>
    </tr>
    <tr>
        <td>
            <a href="{% url 'applausable:show_genre' 'Classical' %}">

                <img src="{% static 'genre_images/Classical.PNG' %}"
                     width="150"
                     height="150" alt="Classical Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Country' %}">

                <img src="{% static 'genre_images/Country.PNG' %}"
                     width="150"
                     height="150" alt="Country Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Indy' %}">

                <img src="{% static 'genre_images/Indy.PNG' %}"
                     width="150"
                     height="150" alt="Indy Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'R&B' %}">

                <img src="{% static 'genre_images/R&B.PNG' %}"
                     width="150"
                     height="150" alt="R&B Image" />

            </a>
        </td>
    </tr>
    <tr>
        <td>
            <a href="{% url 'applausable:show_genre' 'Metal' %}">

                <img src="{% static 'genre_images/Metal.PNG' %}"
                     width="150"
                     height="150" alt="Metal Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Reggae' %}">

                <img src="{% static 'genre_images/Reggae.PNG' %}"
                     width="150"
                     height="150" alt="Reggae Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Hip-Hop' %}">

                <img src="{% static 'genre_images/Hip-Hop.PNG' %}"
                     width="150"
                     height="150" alt="Hip-Hop Image" />

            </a>
        </td>
        <td>
            <a href="{% url 'applausable:show_genre' 'Electronic' %}">

                <img src="{% static 'genre_images/Electronic.PNG' %}"
                     width="150"
                     height="150" alt="Electronic Image" />

            </a>
        </td>
    </tr>
</table>

{% endblock %}

templates/applausable/base.html
<!DOCTYPE html>
{% load staticfiles %}
<!-- #TODO: make template tags but do this when make review forum-->

<html>

    <head>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" 
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <title>
            Appausable -
            {% block title_block %}
                Applausable
            {% endblock %}
        </title>
    </head>
    
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top navbar-dark bg-dark">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home' %}">Applausable</a>
              </div>
              <ul class="nav navbar-nav">
                  {% if user.is_authenticated %}
                  {% if not request.user.is_superuser %}
                  <li><a href="{% url 'applausable:show_user' %}" style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span>Profile </a><a href="{% url 'auth_logout' %}?next={% url 'home' %}" style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
                  {% else %}
                  <li><a href="{% url 'auth_logout' %}?next={% url 'home' %}" style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span> Logout</a></li>
                  {% endif %}
                  {% else %}
                  <li><a href="{% url 'registration_register' %}" style="color:#ffffff;"><span class="glyphicon glyphicon-user"></span>Sign Up </a> <a href="{% url 'auth_login' %}" style="color:#ffffff;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                  {% endif %}
              </ul>
            </div>
		</nav>
  
        <div>
        {% block body_block %}
        {% endblock %}
        </div> 
        <hr />

        
    <!-- Bootstrap core JavaScript -->         
    <!-- Placed at the end of the document so the pages load faster -->         
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>         
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>         
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/applausable/home.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">

<!--
	<div class='container'>
		
		{% if user.is_authenticated %}
		Welcome {{ user.username }}! <a href="{% url 'applausable:show_user'%}">User Page</a>
		{% else %}
		<a href="{% url 'registration_register' %}">Sign Up for Applausable</a>
		{% endif %}
		</h4>
		<strong>{{ boldmessage }}</strong>
	</div>
-->

<div class='jumbotron jumbotron-fluid'>

	<div class='container p-4'>
		<h1 class="jumbotron-heading px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center ">
			Search Applausable For Your Favorite Artists
		</h1>
		<form action="{% url 'applausable:search_results' %}" method="GET" value="{{request.GET.q}}">
			<input type="text" name="q" value="{{request.GET.q}}" placeholder="Search Artists" />	
		</form>
	</div>
</div>

	<div class='container'>
		{% if submitbutton == 'Search' and request.GET.q != '' %}
		{% if results %}
		<h1>Results for <b>{{ request.GET.q }}</b></h1>
		<br />
		<br />
	
		{% for result in results %}
	
		{{result.title}}
		<br />
	
		{{result.content}}
		<br />
	
		{% endfor %}
		{% else %}
		No search results for this query
		{% endif %}
		{% endif %}
		{% if artists %}
	</div>

<div class="container">
	<div class="card text-center">
		<div class="card-header">
			<h3>Current Top Reviewed Song:</h3>
		</div>
		<div class="card-body">
			{% if songs %}
				{% for song in songs %}
					<img src="{{ MEDIA_URL }}{{ song.albumID.albumCover }}" width="400" height="400" alt="{{ song.artistName }}">
					<h4>{{ song.title }}</h4> 
					<h5 class="card-subtitle mb-2 text-muted">by {{song.artistName}}</h5>
					<p class="card-text">This song recieved a score of {{song.overallScore}}.</p>
					<a href="{% url 'applausable:show_song' song.slug %}" class="card-link">Learn More and Review</a>
				{% endfor %}
			{% endif %}  
		</div>
	</div>
	<br />
</div>

<div class="container" allign="centre">
	<div class="row justify-content-md-center">
	<div class="col-md-auto">
	<a href="{% url 'applausable:highestReviewedSongs' %}" class="btn btn-primary">View our song ranking</a>
	<a href="{% url 'applausable:all_genre' %}" class="btn btn-primary">View our song ranking by genre</a>
	<a href="{% url 'applausable:artist' %}" class="btn btn-primary">View all Artists</a>
	</div>
	</div>
</div>

<div class="container">
	{% if request.user.is_superuser %}
		<a class="nav-link active" href="{% url 'applausable:add_artist' %}">
			Add an Artist
		</a>
	
	
	{% endif %}
	{% else %}
	
	<li class="nav-item">There are no artists present.</li>
	{% endif %}
</div>

<!-- Page 225-226 of book has good bootstrap display for artists and songs when it comes to it-->

{% endblock %}

templates/applausable/profile_registration.html
{% extends 'applausable/base.html' %}

{% block title_block %} 
    Register - Image
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Register Here - Profile Picture</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <form method="post" action="{% url 'applausable:register_profile' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create Profile" />
        </form>
    </div>
    <p></p>
</div>

<div class='container'>
    <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
</div>
{% endblock %}

templates/applausable/search_results.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Search Results

{% endblock %}

{% block body_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">
<div class="jumbotron">
    <div class='container'>
            <h1 align="center">Search Results</h1>
        
    </div>
</div>

{% if results %}
<div class='container' algin='center'>
    <div class="img-with-text">
        <table width="500" border="0" cellpadding="5" align="center">
            <tr>
                {% for result in results %}
                <td align="center">
                    <a href="{% url 'applausable:show_artist' result.slug %}">
                        <div class="card">
                            <img src="{{ MEDIA_URL }}{{ result.artistImage }}" width="300" height="300" alt="artist profile image">
                            <div class="card-body">
                              <h5 class="card-title">{{ result.artistName }}</h5>
                            </div>
                        </div>
                    </a>
                </td>
                {% if not forloop.last and forloop.counter|divisibleby:3 %}
            </tr>
            <tr>
                {% endif %}
                {% endfor %}
            </tr>
        </table>
    </div>
</div>
{% else %}
There are no results for your search
{% endif %}
{% endblock %}

templates/applausable/specificArtist.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Specific Artist
{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">
<div class="jumbotron">
    <div class="text-center">
        {% if artist %}
        <h1>{{ artist.artistName }}</h1>
        {% else %}
        <h1>No artist found</h1>
        {% endif %}
    </div>
</div>
<div class="container">
    {% if artist %}
    <br />
    <div class="card">
        <img src="{{ MEDIA_URL }}{{ artist.artistImage }}" class="card-img-top" alt="{{ artist.artistName }}'s profile image">
        <div class="card-body" align="center">
          <h2 class="card-title">{{ artist.artistName }}</h2>
          <p class="card-text">{{ artist.description }}</p>
        </div>
    </div>
        <br />
</div>

<div class="container-fluid">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Song</th>
                <th scope="col">Album</th>
                <th scope="col">Score</th>
                <th scope="col">Link</th>
            </tr>
        </thead>
        <tbody>
            {% if  mostPopularSongs %}
            {% for mSong in mostPopularSongs %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ mSong.title }}</td>
                <td>{{ mSong.albumID.albumName }}</td>
                <td>{{ mSong.overallScore }}</td>
                <td><a class="nav-link active" href="{% url 'applausable:show_song' mSong.slug %}">Song Page</a> </td>
            </tr>
            {% endfor %}
            {% else %}
                No songs found.
            {% endif %}
        </tbody>
    
    {% else %}
    <h1>No artist found</h1>
    {% endif %}
</div>

<div class='container'>
    <p id="test"></p>
    <h2 align="center"> Top Reviewed Songs: </h2>
    
    <div class="img-with-text"></div>
    <table width="150" border="0" cellpadding="5" align="center">
        <tr>
            {% for album in albums %}
            <td align="center">
                <a href="{% url 'applausable:show_album' album.slug %}">
    
                    <img src="{{ MEDIA_URL }}{{ album.albumCover }}"
                         width="250"
                         height="250" alt="Album Cover" />
                    <p>{{ album.albumName }}</p>
                </a>
    
            </td>
            {% if not forloop.last and forloop.counter|divisibleby:3 %}
        </tr>
        <tr>
            {% endif %}
            {% endfor %}
        </tr>
    </table>


	{% if request.user.is_superuser %}
        <br />
        <a href="{% url 'applausable:add_album' artist.slug %}">Add Album</a><br />
    {% endif %}

</div>

<div class="container">
    <br />
    <a href="{% url 'home' %}">
         <p>Back to Home Page</p>
    </a>
</div>

{% endblock %}

templates/applausable/user_page.html
{% extends 'applausable/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ user.username }}'s Profile

{% endblock %}

{% block body_block %}
<link rel="stylesheet" type="text/css" href="{% static 'css/general.css' %}">
<script type="text/javascript">var email = "{{user.email}}";</script>

<script type="text/javascript" src="{% static 'js/email_button.js' %}"></script>


<div class="jumbotron">
    <div class='container'>
        {% if profile.picture %}
        <img src="{{ MEDIA_URL }}{{ profile.picture }}" width="300" height="300"
             alt="{{ user.username }}'s profile image" />
        {% endif %}

        <h1>{{ user.username }}'s Profile</h1>

    </div>
</div>


<div class="container">
    <p align="left"><button type="button" class="btn btn-outline-secondary" onclick="myFunction()">Click To reveal sensitive information</button></p>
	<div class='comments' align="left" style="padding: 10px;">
        <p class="font-weight-bold">
            Your website: <a href={{ profile.website }}>{{ profile.website}}</a>
            <span class=" text-muted font-weight-normal"></span>
        </p>
        </br>
        <p class="font-weight-bold">
            <div id="myDIV" class="font-weight-bold">Your email:</div>
            <span class=" text-muted font-weight-normal"></span>
        </p>
    </div>
</div>

<script>

</script>
<div class="container">
    <div class="row">
        <div class="card" style="width: 85rem; max-height:55rem; overflow:auto;">
            <div class="card-header">
                Reviews:
            </div>
            <ul class="list-group list-group-flush">
                {% for review in reviews %}
                <li class="list-group-item">
                    <p class="font-weight-bold">
					    
						<a  href="{% url 'applausable:show_song' review.songID.slug %}">
						{{ review.songID.title }} </a>
						({{ review.score }}/10): <br />
						By <a  href="{% url 'applausable:show_artist' review.songID.artistID.slug %}">
						 {{ review.songID.artistName }} </a>

                    </p>
                    {{ review.review | linebreaks }}</li>
                    {% endfor %}
                </ul>
            </div>
            <br />

    </div>
</div>


{% endblock %}

templates/applausable/youtubeTest.html
<!DOCTYPE html>
<html>
<body>
    <!-- 1. The <iframe> (and video player) will replace this <div> tag. -->
    <div id="player"></div>

    <script>
        // 2. This code loads the IFrame Player API code asynchronously.
        var tag = document.createElement('script');

        tag.src = "https://www.youtube.com/iframe_api";
        var firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        // 3. This function creates an <iframe> (and YouTube player)
        //    after the API code downloads.
        var player;
        function onYouTubeIframeAPIReady() {
            player = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: 'M7lc1UVf-VE',
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
            });
        }

        // 4. The API will call this function when the video player is ready.
        function onPlayerReady(event) {
            event.target.playVideo();
        }

        // 5. The API calls this function when the player's state changes.
        //    The function indicates that when playing a video (state=1),
        //    the player should play for six seconds and then stop.
        var done = false;
        function onPlayerStateChange(event) {
            if (event.data == YT.PlayerState.PLAYING && !done) {
                setTimeout(stopVideo, 0);
                done = true;
            }
        }
        function youtube_parser(url){
            var regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#&?]*).*/;
            var match = url.match(regExp);
            return (match&&match[7].length==11)? match[7] : false;
}
        function stopVideo() {
            player.stopVideo();
        }
        var player;
        function onYouTubeIframeAPIReady() {
        
    player = new YT.Player('player', {
    height: '390',
    width: '640',
    videoId: youtube_parser('https://www.youtube.com/watch?v=tPgf_btTFlc'),
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
}
    </script>

</body>
</html>